x-logging:
    &default-logging
    driver: "json-file"
    options:
        max-size: "10m"
        max-file: "3"

networks:
  mailnet:
    external: true

services:
  nzbget:
    extends:
       file: docker-compose.yml
       service: nzbget
  spotweb:
    extends: 
       file: docker-compose.yml
       service: spotweb
    environment:
     - SPOTWEB_DB_TYPE=pdo_pgsql
     - SPOTWEB_DB_PORT=5432
     - SPOTWEB_DB_USER=postgres
    volumes:
     - ${SPOTWEBVOLUME}/spotweb:/config
    depends_on:
     - db
    logging: *default-logging

  db:
    image: postgres:latest
    container_name: spotwebdb
    networks:
      - mailnet
    hostname: spotwebdb
    restart: unless-stopped
    environment:
     - TZ=Europe/Amsterdam
     - POSTGRES_PASSWORD=spotweb
     - POSTGRES_DB=spotweb
    volumes:
     - ${SPOTWEBVOLUME}/db:/var/lib/postgresql/data
    ports:
     - 5432:5432
    logging: *default-logging

  pgadmin4:
    image: tgiesela/pgadmin4:latest
    build: pgadmin/.
    container_name: pgadmin4
    networks:
      - mailnet
    hostname: pgadmin
    restart: unless-stopped
    environment:
     - TZ=Europe/Amsterdam
     - PGADMINEMAIL=${PGADMINEMAIL}
     - PGADMINPASSWORD=${PGADMINPASSWORD}
     - PGADMINPORT=${PGADMINPORT}
     - MAIL_SERVER=${MAIL_SERVER}
     - MAIL_PORT=${MAIL_PORT}
     - MAIL_USE_SSL=${MAIL_USE_SSL}
     - MAIL_USE_TLS=${MAIL_USE_TLS}
     - MAIL_USERNAME=${MAIL_USERNAME}
     - MAIL_PASSWORD=${MAIL_PASSWORD}
    depends_on:
     - db
    ports:
     - 8081:${PGADMINPORT}
    volumes:
     - ${SPOTWEBVOLUME}/pgadmin4:/config
    logging: *default-logging
    labels:
      - "com.tgiesela.vpn.accessible=true"
      - "com.tgiesela.vpn.vpnport=8081"
      - "com.tgiesela.vpn.containerport=${PGADMINPORT}"
