version: "2.1"
services:
  spotweb:
    image: tgiesela/spotweb
    build: ./spotweb
    container_name: spotweb
    restart: unless-stopped
    environment:
     - PUID=1001
     - GUID=1001
     - TZ=Europe/Amsterdam
     - SPOTWEB_DB_TYPE=pdo_mysql
     - SPOTWEB_DB_HOST=spotwebdb
     - SPOTWEB_DB_PORT=3306
     - SPOTWEB_DB_NAME=spotweb
     - SPOTWEB_DB_USER=spotweb
     - SPOTWEB_DB_PASS=spotweb
     - "SPOTWEB_CRON_RETRIEVE=*/5 * * * *"
    depends_on:
     - spotweb_db
    ports:
     - 8085:80
    volumes:
     - /dockerdata/spotweb:/config

  spotweb_db:
    image: tgiesela/db
    build: ./mariadb/
    container_name: spotwebdb
    hostname: spotwebdb
    restart: unless-stopped
    environment:
     - PUID=1001
     - PGID=1001
     - TZ=Europe/Amsterdam
     - MYSQL_ROOT_PASSWORD=spotweb
     - MYSQL_DATABASE=spotweb
     - MYSQL_USER=spotweb
     - MYSQL_PASSWORD=spotweb
    volumes:
     - /dockerdata/mariadb:/config
    ports:
     - 3306:3306

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
     - TZ=Europe/Amsterdam
     - MYSQL_ROOT_PASSWORD=spotweb
     - PMA_HOST=spotwebdb
    ports:
     - 8080:80

