version: "2.1"
services:
  spotweb:
    environment:
     - SPOTWEB_DB_TYPE=pdo_pgsql
     - SPOTWEB_DB_PORT=5432
     - SPOTWEB_DB_USER=postgres
    volumes:
     - ${SPOTWEBVOLUME}/spotweb:/config
    depends_on:
     - db

  db:
    image: postgres
    container_name: spotwebdb
    hostname: spotwebdb
    restart: unless-stopped
    environment:
     - TZ=Europe/Amsterdam
     - POSTGRES_PASSWORD=spotweb
     - POSTGRES_DB=spotweb
    volumes:
     - ${SPOTWEBVOLUME}/db:/var/lib/postgresql/data
    ports:
     - 5432:5432
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

#  admin:
#    image: adminer
#    container_name: postgresadmin
#    restart: unless-stopped
#    environment:
#     - TZ=Europe/Amsterdam
#    depends_on:
#     - db
#    ports:
#     - 8080:8080

  pgadmin4:
    image: tgiesela/pgadmin4:latest
    build: pgadmin/.
    container_name: pgadmin4
    restart: unless-stopped
    environment:
     - TZ=Europe/Amsterdam
     - PGADMINEMAIL=${PGADMINEMAIL}
     - PGADMINPASSWORD=${PGADMINPASSWORD}
     - MAIL_SERVER=${MAIL_SERVER}
     - MAIL_PORT=${MAIL_PORT}
     - MAIL_USE_SSL=${MAIL_USE_SSL}
     - MAIL_USE_TLS=${MAIL_USE_TLS}
     - MAIL_USERNAME=${MAIL_USERNAME}
     - MAIL_PASSWORD=${MAIL_PASSWORD}
    depends_on:
     - db
    ports:
     - 8080:80
    volumes:
     - ${SPOTWEBVOLUME}/pgadmin4:/config
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
