x-logging:
    &default-logging
    driver: "json-file"
    options:
        max-size: "10m"
        max-file: "3"

services:
  spotweb:
    image: tgiesela/spotweb:v2
    build: ./spotweb
    container_name: spotweb
    hostname: spotweb
    restart: unless-stopped
    environment:
     - PUID=1001
     - GUID=1001
     - TZ=Europe/Amsterdam
     - SPOTWEB_DB_TYPE=pdo_mysql
     - SPOTWEB_DB_HOST=spotwebdb
     - SPOTWEB_DB_PORT=3306
     - SPOTWEB_DB_NAME=spotweb
     - SPOTWEB_DB_USER=postgres
     - SPOTWEB_DB_PASS=spotweb
     - "SPOTWEB_CRON_RETRIEVE=*/5 * * * *"
    networks:
      - mailnet
    ports:
     - 8085:80
    volumes:
     - ${SPOTWEBVOLUME}/spotweb:/config
    depends_on:
      - vpn
    logging: *default-logging
    labels:
      - "com.tgiesela.vpn.accessible=true"
      - "com.tgiesela.vpn.vpnport=8085"
      - "com.tgiesela.vpn.containerport=80"

  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    hostname: nzbget
    networks: [mailnet]
    ports:
      - 6789:6789
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=Europe/Amsterdam
      - NZBGET_USER=nzbget #optional
      - NZBGET_PASS=tegbzn6789 #optional
    volumes:
      - ${NZBGETVOLUME}/data:/config
      - ${DOWNLOADVOLUME}:/downloads #optional
    depends_on: 
      - vpn
    restart: always
    logging: *default-logging
    labels:
      - "com.tgiesela.vpn.accessible=true"
      - "com.tgiesela.vpn.vpnport=6789"
      - "com.tgiesela.vpn.containerport=6789"

  samba:
    image: tgiesela/samba:latest
    build: ./samba
    container_name: samba
    hostname: samba
    networks: [mailnet]
    ports:
      - 139:139
      - 445:445
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - ${SAMBAVOLUME}:/config
      - ${DOWNLOADVOLUME}:/download
      - ${SAMBAVOLUME}/smb.conf:/etc/samba/smb.conf
    depends_on:
      - vpn
    restart: always
    logging: *default-logging
    labels:
      - "com.tgiesela.vpn.accessible=true"
      - "com.tgiesela.vpn.vpnport=139;445"
      - "com.tgiesela.vpn.containerport=139:445"

networks:
   mailnet:
      external: true
