x-logging:
    &default-logging
    driver: "json-file"
    options:
        max-size: "10m"
        max-file: "3"

networks:
  mailnet:
    external: true

services:
  spotweb:
    extends: 
       file: docker-compose.yml
       service: spotweb
    environment:
     - SPOTWEB_DB_TYPE=pdo_mysql
     - SPOTWEB_DB_PORT=3306
     - SPOTWEB_DB_USER=postgres
    volumes:
     - ${SPOTWEBVOLUME}/mysql/spotweb:/config
    depends_on:
     - db
    logging: *default-logging

  db:
    image: mysql
    container_name: spotwebdb
    hostname: spotwebdb
    restart: unless-stopped
    environment:
     - TZ=Europe/Amsterdam
     - PUID=1001
     - MYSQL_ROOT_PASSWORD=spotweb
     - MYSQL_DATABASE=spotweb
    volumes:
     - ${SPOTWEBVOLUME}/mysql/db:/var/lib/postgresql/data
    ports:
     - 3306:3306
    logging: *default-logging

