version: "2.1"
services:
  spotweb:
    environment:
     - SPOTWEB_DB_TYPE=pdo_pgsql
     - SPOTWEB_DB_PORT=5432
     - SPOTWEB_DB_USER=postgres
    volumes:
     - ${SPOTWEBVOLUME}/postgres/spotweb:/config
    depends_on:
     - db

  db:
    image: postgres
    container_name: spotwebdb
    hostname: spotwebdb
    restart: unless-stopped
    environment:
     - TZ=Europe/Amsterdam
     - POSTGRES_PASSWORD=spotweb
     - POSTGRES_DB=spotweb
    volumes:
     - ${SPOTWEBVOLUME}/postgres/db:/var/lib/postgresql/data
    ports:
     - 5432:5432

#  admin:
#    image: adminer
#    container_name: postgresadmin
#    restart: unless-stopped
#    environment:
#     - TZ=Europe/Amsterdam
#    depends_on:
#     - db
#    ports:
#     - 8080:8080

  pgadmin:
    image: tgiesela/pgadmin4
    build: pgadmin/.
    container_name: pgadmin4
    hostname: pgadmin4
    environment:
     - TZ=Europe/Amsterdam
    depends_on:
     - db
    ports:
     - 8080:80
   
