version: "2.1"
services:
  spotweb:
    image: tgiesela/spotweb:latest
    build: ./spotweb
    container_name: spotweb
    restart: unless-stopped
    environment:
     - PUID=1001
     - GUID=1001
     - TZ=Europe/Amsterdam
     - SPOTWEB_DB_TYPE=pdo_mysql
     - SPOTWEB_DB_HOST=spotwebdb
     - SPOTWEB_DB_PORT=3306
     - SPOTWEB_DB_NAME=spotweb
     - SPOTWEB_DB_USER=postgres
     - SPOTWEB_DB_PASS=spotweb
     - "SPOTWEB_CRON_RETRIEVE=*/5 * * * *"
    ports:
     - 8085:80
    volumes:
     - ${SPOTWEBVOLUME}/spotweb:/config


