x-logging:
    &default-logging
    driver: "json-file"
    options:
        max-size: "10m"
        max-file: "3"

services:
  spotweb:
    image: tgiesela/spotweb:v2
    build: ./spotweb
    container_name: spotweb
    hostname: spotweb
    restart: on-failure:5
    environment:
     - PUID=1001
     - GUID=1001
     - TZ=Europe/Amsterdam
     - SPOTWEB_DB_TYPE=pdo_mysql
     - SPOTWEB_DB_HOST=spotwebdb
     - SPOTWEB_DB_PORT=3306
     - SPOTWEB_DB_NAME=spotweb
     - SPOTWEB_DB_USER=postgres
     - SPOTWEB_DB_PASS=spotweb
     - "SPOTWEB_CRON_RETRIEVE=*/5 * * * *"
    networks:
      - mailnet
    dns: [ $DNSIP ]
    ports:
     - 8085:80
    volumes:
     - ${SPOTWEBVOLUME}/spotweb:/config
    logging: *default-logging
    labels:
      - "com.tgiesela.vpn.hiddenip=true"
      - "com.tgiesela.vpn.accessible=true"
      - "com.tgiesela.vpn.vpnport=8085"
      - "com.tgiesela.vpn.containerport=80"

  nzbget:
    image: tgiesela/nzbget:latest
    build: ./nzbget
    container_name: nzbget
    hostname: nzbget
    networks: [mailnet]
    dns: [ $DNSIP ]
    ports:
      - 6789:6789
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - ${NZBGETVOLUME}/data:/config
      - ${DOWNLOADVOLUME}:/downloads 
    restart: on-failure:5
    logging: *default-logging
    labels:
      - "com.tgiesela.vpn.hiddenip=true"
      - "com.tgiesela.vpn.accessible=true"
      - "com.tgiesela.vpn.vpnport=6789"
      - "com.tgiesela.vpn.containerport=6789"

  samba:
    image: tgiesela/samba:latest
    build: ./samba
    container_name: samba
    hostname: samba
    networks: [mailnet]
    dns: [ $DNSIP ]
    ports:
      - 139:139/tcp
      - 137:137/udp
      - 138:138/udp
      - 445:445/tcp
    environment:
      - TZ=Europe/Amsterdam
      - SAMBA_ROOT_PASSWORD=${SAMBA_ROOT_PASSWORD}
    volumes:
      - ${SAMBAVOLUME}:/config
      - ${SHAREDDATA}:${SHAREDDATA}
      - ${SAMBAVOLUME}/smb.conf:/etc/samba/smb.conf
    restart: on-failure:5
    logging: *default-logging
    labels:
      - "com.tgiesela.vpn.accessible=true"
      - "com.tgiesela.vpn.vpnport=139;445"
      - "com.tgiesela.vpn.containerport=139;445"

networks:
  mailnet:
    name: mailnet
    external: true
